import type { Metadata } from "next";
import { Inter, Roboto_Mono, Poppins, Karla } from "next/font/google";

import "./globals.css";

// Use valid Next.js fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: "400", // Regular weight
  subsets: ["latin"],
});

const karla = Karla({
  weight: "400", // Regular weight
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

// Global metadata for all pages
export const metadata: Metadata = {
  title: "CreteraREST",
  description: "A description of your app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />
        {/* You can also add meta description or any other global head elements */}
        <meta name="description" content="Generated by create next app" />
      </head>
      <body
        className={`${inter.variable} ${robotoMono.variable} ${poppins.className} ${karla.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
